language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
before_script:
  - "flake8 --benchmark --statistics --count keynoteapi/ *.py"
  - "flake8 --benchmark --statistics --count --ignore E712,E501,E711,E211 tests"
script:
  - "python setup.py nosetests"
after_script:
  - "coveralls --verbose"
notifications:
  email:
    - normes@normes.org
